# Generated by Django 2.2.10 on 2021-12-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[(1, 'Radiobutton'), (2, 'Multiple'), (3, 'Text')], default=1, max_length=8),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateTimeField(verbose_name='start date'),
        ),
    ]
