# Generated by Django 2.2.10 on 2021-12-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20211207_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.IntegerField(choices=[(1, 'Radiobutton'), (2, 'Multiple'), (3, 'Text')], default=1, max_length=8),
        ),
    ]
