# Generated by Django 2.2.10 on 2021-12-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20211207_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.IntegerField(choices=[(1, 'Radiobutton'), (2, 'Multiple'), (3, 'Text')], default=1),
        ),
    ]
