# Generated by Django 2.2.10 on 2021-12-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20211208_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
