# Generated by Django 2.2.10 on 2021-12-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_answer_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
